version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 852518815216.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t realwordrepo .
      - docker tag realwordrepo:latest 852518815216.dkr.ecr.us-east-1.amazonaws.com/realwordrepo:latest     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 852518815216.dkr.ecr.us-east-1.amazonaws.com/realwordrepo:latest
