version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Github...
      - docker login -u abhi9929 -p Abhi@9929712767
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t abhi9929/nodeapp:latest .
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push abhi9929/nodeapp:latest
